/* Auto generated file by build envsetup shell.
 !!!!!!!! Do not edit this file. !!!!!!!!
 Created time : Mon Jan  5 16:29:59 KST 2015
TARGET_BUILD_BOARDVER : tp20
*/

#define CONFIG_BOARD_VER CONFIG_TP20

